#ifndef __FACE_MODEL_DATA_H__
#define __FACE_MODEL_DATA_H__

//this file is generated by tflite2c.py

#include <stdint.h>
extern const unsigned char g_face_model_data[];
extern const unsigned int g_face_model_data_len;

#endif
