#ifndef __WU_20_MODEL_DATA_H__
#define __WU_20_MODEL_DATA_H__

//this file is generated by tflite2c.py


#include <stdint.h>
extern const unsigned char WU_20_model_data[];
extern const unsigned int WU_20_model_data_len;
extern const char* WU_20_model_classes[];
extern const unsigned int WU_20_model_classes_num;

#endif


